// File generated by FlutterFire CLI.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;

      case TargetPlatform.windows:
        return windows;

      case TargetPlatform.linux:
        return linux;

      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );

      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );

      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyBBkS6SalgIPTE8HQqadKoACPmpVNx6rds",

    authDomain: "batalha-naval-62fa5.firebaseapp.com",

    projectId: "batalha-naval-62fa5",

    storageBucket: "batalha-naval-62fa5.firebasestorage.app",

    messagingSenderId: "1066863263308",

    appId: "1:1066863263308:web:ab75a89c26ce8f817f3ee9",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyBBkS6SalgIPTE8HQqadKoACPmpVNx6rds",

    authDomain: "batalha-naval-62fa5.firebaseapp.com",

    projectId: "batalha-naval-62fa5",

    storageBucket: "batalha-naval-62fa5.firebasestorage.app",

    messagingSenderId: "1066863263308",

    appId: "1:1066863263308:web:ab75a89c26ce8f817f3ee9",
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: "AIzaSyBBkS6SalgIPTE8HQqadKoACPmpVNx6rds",

    authDomain: "batalha-naval-62fa5.firebaseapp.com",

    projectId: "batalha-naval-62fa5",

    storageBucket: "batalha-naval-62fa5.firebasestorage.app",

    messagingSenderId: "1066863263308",

    appId: "1:1066863263308:web:ab75a89c26ce8f817f3ee9",
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: "AIzaSyBBkS6SalgIPTE8HQqadKoACPmpVNx6rds",

    authDomain: "batalha-naval-62fa5.firebaseapp.com",

    projectId: "batalha-naval-62fa5",

    storageBucket: "batalha-naval-62fa5.firebasestorage.app",

    messagingSenderId: "1066863263308",

    appId: "1:1066863263308:web:ab75a89c26ce8f817f3ee9",
  );
}
